### ISSUE TITLE
Add static analysis to the repository

### ISSUE THREAD

**Issue by cdevoogd** [cdevoogd/apollo#33]
Because Apollo is being rewritten, now is a good time to start with static analysis. In previous projects, I have used [DeepSource](https://deepsource.io/) for static analysis. A possible configuration could look something like this:

```toml
version = 1

test_patterns = [
    "test/**",
    "**/*_test.go"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/cdevoogd/apollo"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true
```
